spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/project_user
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate.ddl-auto: update
    show-sql: true
    properties.hibernate.format_sql: true
    properties.hibernate.dialect: org.hibernate.dialect.PostgreSQL81Dialect
